_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  block: 0
  breakpoint: 0
  dblog: 0
  dynamic_page_cache: 0
  field: 0
  filter: 0
  node: 0
  page_cache: 0
  path_alias: 0
  system: 0
  text: 0
  toolbar: 0
  update: 0
  user: 0
  htmx: 1000
theme:
  stable: 0
  classy: 0
  pico_htmx: 0
profile: htmx
