version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "8-buster"
        NODE_VERSION: "lts/*"
    volumes:
      - ..:/workspace:cached
    network_mode: service:db
    depends_on:
      db:
        condition: service_healthy
    command: apache2-foreground
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: mariadb
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb

  db:
    image: mariadb:10.4
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysql -umariadb -pmariadb -e 'use mariadb' || exit 1"]
      interval: 3s
      timeout: 60s
      retries: 40
      start_period: 20s
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: mariadb
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb

volumes:
  mariadb-data: null
